import type { DirectorProfessional } from './types'

/** Equipe ROM Brasil (portfólio 2026) — IDs Avec entram quando a planilha oficial chegar. */
export const BRASIL_DIRECTOR_PROFESSIONALS: DirectorProfessional[] = [
  { id: 'pro-vitor-m', name: 'Vitor M', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-alan-albuquerque', name: 'Alan Albuquerque', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-aline-jabur', name: 'Aline Jabur', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-alison-alvarez', name: 'Alison Alvarez', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-allan-ortega', name: 'Allan Ortega', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-bruna-mello', name: 'Bruna Mello', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-dani-mariniello', name: 'Dani Mariniello', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-day-marques', name: 'Day Marques', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-derley-silva', name: 'Derley Silva', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-diego-marcsant', name: 'Diego Marcsant', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-diogo-pitaro', name: 'Diogo Pitaro', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-douglas-garcia', name: 'Douglas Garcia', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-elvis-teixeira', name: 'Elvis Teixeira', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-gabriel-john', name: 'Gabriel John', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-gustavo-colonno', name: 'Gustavo Colonno', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-henrique-tenorio', name: 'Henrique Tenório', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-jander-barros', name: 'Jander Barros', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-leonardo-tomaz', name: 'Leonardo Tomáz', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-leonel-claret', name: 'Leonel Claret', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-lucas-kampos', name: 'Lucas Kampos', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-lucas-sales', name: 'Lucas Sales', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-luiza-britto', name: 'Luiza Britto', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-mauricio-carvalho', name: 'Maurício Carvalho', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-nanda-gomes', name: 'Nanda Gomes', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-neto-campos', name: 'Neto Campos', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-nildo-oliveira', name: 'Nildo Oliveira', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-romeu-felipe', name: 'Romeu Felipe', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-walter-leal', name: 'Walter Leal', avec_pro_id: null, role: 'hairstylist', active: true },
  { id: 'pro-luiza-amaro', name: 'Luiza Amaro', avec_pro_id: null, role: 'makeup', active: true },
  { id: 'pro-marina-mattar', name: 'Marina Mattar', avec_pro_id: null, role: 'makeup', active: true },
]
